/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Dao.UserDao;
import model.User;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
/**
 *
 * @author ASUS
 */
public final class SignUppage2 extends javax.swing.JFrame {

    
    /**
     * Creates new form SignUppage2
     */
    public SignUppage2() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Email_Field = new javax.swing.JTextField();
        Username_Field = new javax.swing.JTextField();
        Password_Field = new javax.swing.JTextField();
        Phone_Field = new javax.swing.JTextField();
        Address_Field = new javax.swing.JTextField();
        MedicalHistory_Field = new javax.swing.JTextField();
        SignUp_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Gender_Field = new javax.swing.JComboBox<>();
        BloodGroup_Field = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.jpeg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.jpeg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("SignUp");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 134, 80, -1));

        Email_Field.setText("Email");
        Email_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_FieldFocusLost(evt);
            }
        });
        Email_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_FieldActionPerformed(evt);
            }
        });
        jPanel1.add(Email_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 179, 150, -1));

        Username_Field.setText("Username");
        Username_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Username_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Username_FieldFocusLost(evt);
            }
        });
        Username_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_FieldActionPerformed(evt);
            }
        });
        jPanel1.add(Username_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 229, 153, -1));

        Password_Field.setText("Password");
        Password_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_FieldFocusLost(evt);
            }
        });
        jPanel1.add(Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 279, 153, -1));

        Phone_Field.setText("Phone no.");
        Phone_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Phone_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Phone_FieldFocusLost(evt);
            }
        });
        jPanel1.add(Phone_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 329, 153, -1));

        Address_Field.setText("Address");
        Address_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Address_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Address_FieldFocusLost(evt);
            }
        });
        jPanel1.add(Address_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 179, 153, -1));

        MedicalHistory_Field.setText("Medical History");
        MedicalHistory_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MedicalHistory_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MedicalHistory_FieldFocusLost(evt);
            }
        });
        jPanel1.add(MedicalHistory_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 329, 153, -1));

        SignUp_Button.setText("Sign Up");
        SignUp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SignUp_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 385, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Blood Link logo (2).jpeg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, 30));

        Gender_Field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Others" }));
        jPanel1.add(Gender_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        BloodGroup_Field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blood Group", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel1.add(BloodGroup_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 660, 470));

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 625, 455));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_ButtonActionPerformed
        // TODO add your handling code here:
       System.out.println("Button Clicked");

    String email = Email_Field.getText();
    String username = Username_Field.getText();
    String password = Password_Field.getText();
    String phone = Phone_Field.getText();
    String address=Address_Field.getText();
    JComboBox<String> genderCombo = new JComboBox<>(new String[] { "Male", "Female", "Other" });

// To get selected gender:
String selectedGender = genderCombo.getSelectedItem().toString();

   JComboBox<String> bloodTypeCombo = new JComboBox<>(new String[] { "A+", "B+", "O+", "AB+" });
String selectedBloodGroup = bloodTypeCombo.getSelectedItem().toString();

    String medical_history=MedicalHistory_Field.getText();
    

    System.out.println("Collected user data");

    try {
        User user = new User(email, username, password, phone, address, selectedGender, selectedBloodGroup, medical_history);
        UserDao userDao = new UserDao();

        System.out.println("Attempting registration");
        boolean isRegistered = userDao.registerUser(user);

        if (isRegistered) {
            System.out.println("User registered successfully");
            JOptionPane.showMessageDialog(this, "Registration successful!");
            this.dispose();
        } else {
            System.out.println("User already exists or registration failed");
            JOptionPane.showMessageDialog(this, "User already exists or registration failed.");
        }

    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
        e.printStackTrace();
    }
        
        
    }//GEN-LAST:event_SignUp_ButtonActionPerformed

    private void Username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_FieldActionPerformed

    private void Email_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_FieldFocusGained
        // TODO add your handling code here:if
        if (Email_Field.getText().equals("Email")) {
        Email_Field.setText("");
    }
    }//GEN-LAST:event_Email_FieldFocusGained

    private void Email_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_FieldFocusLost
        // TODO add your handling code here:
        if (Email_Field.getText().isEmpty()) {
        Email_Field.setText("Email");
    }
    }//GEN-LAST:event_Email_FieldFocusLost

    private void Email_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_FieldActionPerformed

    private void Username_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_FieldFocusGained
        // TODO add your handling code here:
       if (Username_Field.getText().equals("Username")) {
        Username_Field.setText("");
    }
    }//GEN-LAST:event_Username_FieldFocusGained

    private void Username_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_FieldFocusLost
        // TODO add your handling code here:
       if (Username_Field.getText().isEmpty()) {
        Username_Field.setText("Username");
    }
    }//GEN-LAST:event_Username_FieldFocusLost

    private void Password_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_FieldFocusGained
        // TODO add your handling code here:
         if (Password_Field.getText().equals("Password")) {
        Password_Field.setText("");
    }
    }//GEN-LAST:event_Password_FieldFocusGained

    private void Password_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_FieldFocusLost
        // TODO add your handling code here:
         if (Password_Field.getText().isEmpty()) {
        Password_Field.setText("Password");
    }
    }//GEN-LAST:event_Password_FieldFocusLost

    private void Phone_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Phone_FieldFocusGained
        // TODO add your handling code here:
         if (Phone_Field.getText().equals("Phone no.")) {
        Phone_Field.setText("");
    }
    }//GEN-LAST:event_Phone_FieldFocusGained

    private void Phone_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Phone_FieldFocusLost
        // TODO add your handling code here:
         if (Phone_Field.getText().isEmpty()) {
        Phone_Field.setText("Phone no.");
    }
    }//GEN-LAST:event_Phone_FieldFocusLost

    private void Address_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Address_FieldFocusGained
        // TODO add your handling code here:
          if (Address_Field.getText().equals("Address")) {
        Address_Field.setText("");
    }
    }//GEN-LAST:event_Address_FieldFocusGained

    private void Address_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Address_FieldFocusLost
        // TODO add your handling code here:
         if (Address_Field.getText().isEmpty()) {
        Address_Field.setText("Address");
    }
    }//GEN-LAST:event_Address_FieldFocusLost

    private void MedicalHistory_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MedicalHistory_FieldFocusGained
        // TODO add your handling code here:
        if (MedicalHistory_Field.getText().equals("Medical History")) {
        MedicalHistory_Field.setText("");
    }
    }//GEN-LAST:event_MedicalHistory_FieldFocusGained

    private void MedicalHistory_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MedicalHistory_FieldFocusLost
        // TODO add your handling code here
        if (MedicalHistory_Field.getText().isEmpty()) {
        MedicalHistory_Field.setText("Medical History");
    }
    }//GEN-LAST:event_MedicalHistory_FieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUppage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUppage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUppage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUppage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignUppage2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address_Field;
    private javax.swing.JComboBox<String> BloodGroup_Field;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JComboBox<String> Gender_Field;
    private javax.swing.JTextField MedicalHistory_Field;
    private javax.swing.JTextField Password_Field;
    private javax.swing.JTextField Phone_Field;
    private javax.swing.JButton SignUp_Button;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
// 👇 Add this inside SignUppage2 class
public boolean isPasswordSecure(String password) {
    if (password.length() < 8) return false;

    boolean hasUpper = false, hasLower = false, hasDigit = false, hasSpecial = false;

    for (char ch : password.toCharArray()) {
        if (Character.isUpperCase(ch)) hasUpper = true;
        else if (Character.isLowerCase(ch)) hasLower = true;
        else if (Character.isDigit(ch)) hasDigit = true;
        else if ("!@#$%^&*()_+-=[]{}|;':\",.<>?/`~".contains(Character.toString(ch))) hasSpecial = true;
    }

    return hasUpper && hasLower && hasDigit && hasSpecial;
}

}

