/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BloodStoryController;
import model.BloodStoryModel;
import javax.swing.*;
import java.awt.*;
import java.util.List;
 

/**
 *
 * @author ACER
 */
public class Blood_Stories extends javax.swing.JFrame {
//        private JTextArea storyTextArea;

    /**
     * Creates new form Blood_Stories
     */
    public Blood_Stories() {
        initComponents();
        loadStories();
        setLocationRelativeTo(null);
    }
    
     private void loadStories() {
    List<BloodStoryModel> stories = BloodStoryController.fetchAllStories();

        JTextArea[] textAreas = {
            jTextArea1, jTextArea2, jTextArea3,
            jTextArea4, jTextArea5, jTextArea6
        };

        System.out.println("Stories size: " + stories.size()); // Debug print

        for (int i = 0; i < textAreas.length; i++) {
            JTextArea ta = textAreas[i];
            ta.setEditable(false);
            ta.setFont(new Font("Segoe UI", Font.PLAIN, 14));  // consistent font style for visibility
            ta.setLineWrap(true);
            ta.setWrapStyleWord(true);

            if (i < stories.size()) {
                BloodStoryModel story = stories.get(i);

                // Debug print each story content to console
                System.out.println("Story " + i + " user: " + story.getUsername());
                System.out.println("Story " + i + " text: " + story.getStory());

                String storyText = (story.getStory() != null) ? story.getStory().trim() : "";
                String usernameText = (story.getUsername() != null) ? story.getUsername().trim() : "Unknown";

                if (storyText.isEmpty()) {
                    ta.setText("No story available.");
                } else {
                    String content = "Shared by: " + usernameText + "\n\n" + storyText;
                    ta.setText(content);
                }
            } else {
                ta.setText("No story available.");
            }
        
        }
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Home_Field = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Campaign_Field = new javax.swing.JButton();
        Banks_Feild = new javax.swing.JButton();
        Emergency_Field = new javax.swing.JButton();
        Donate_Field = new javax.swing.JButton();
        Request_Field = new javax.swing.JButton();
        Profile_Field = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Blood Link logo (2).jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        Home_Field.setText("Home");
        Home_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Home_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 13, -1, -1));

        jButton2.setText("Blood Stories");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 13, -1, -1));

        Campaign_Field.setText("Campaign Details");
        Campaign_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campaign_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Campaign_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 13, -1, -1));

        Banks_Feild.setText("Blood Banks");
        Banks_Feild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Banks_FeildActionPerformed(evt);
            }
        });
        getContentPane().add(Banks_Feild, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 13, -1, -1));

        Emergency_Field.setText("Emergency Requests");
        Emergency_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emergency_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Emergency_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 13, -1, -1));

        Donate_Field.setBackground(new java.awt.Color(255, 0, 51));
        Donate_Field.setText("Donate");
        Donate_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Donate_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 4, -1, 32));

        Request_Field.setBackground(new java.awt.Color(255, 0, 0));
        Request_Field.setText("Request");
        Request_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Request_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Request_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 4, -1, 32));

        Profile_Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profile_icon.png"))); // NOI18N
        Profile_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 4, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Blood Stories");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("A single pint can save three lives, a single gesture can create a million smiles.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 116, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setColumns(20);
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea5);

        jTextArea6.setColumns(20);
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setWrapStyleWord(true);
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_FieldActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard=new Dashboard();
         dashboard.setVisible(true);
    }//GEN-LAST:event_Home_FieldActionPerformed

    private void Profile_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_FieldActionPerformed
        // TODO add your handling code here:
        Profile profile=new Profile();
        profile.setVisible(true);
    }//GEN-LAST:event_Profile_FieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Campaign_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campaign_FieldActionPerformed
        // TODO add your handling code here:
        CampaignDetails campaign=new CampaignDetails();
        campaign.setVisible(true);
    }//GEN-LAST:event_Campaign_FieldActionPerformed

    private void Banks_FeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Banks_FeildActionPerformed
        // TODO add your handling code here:
        BloodBanks banks=new BloodBanks();
        banks.setVisible(true);
    }//GEN-LAST:event_Banks_FeildActionPerformed

    private void Emergency_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emergency_FieldActionPerformed
        // TODO add your handling code here:
        EmergencyRequest emergency=new EmergencyRequest();
        emergency.setVisible(true);
    }//GEN-LAST:event_Emergency_FieldActionPerformed

    private void Donate_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_FieldActionPerformed
        // TODO add your handling code here:
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_Donate_FieldActionPerformed

    private void Request_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Request_FieldActionPerformed
        // TODO add your handling code here:
        request Request=new request();
        Request.setVisible(true);
    }//GEN-LAST:event_Request_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new Blood_Stories().setVisible(true));
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Blood_Stories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Blood_Stories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Blood_Stories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Blood_Stories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Blood_Stories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Banks_Feild;
    private javax.swing.JButton Campaign_Field;
    private javax.swing.JButton Donate_Field;
    private javax.swing.JButton Emergency_Field;
    private javax.swing.JButton Home_Field;
    private javax.swing.JButton Profile_Field;
    private javax.swing.JButton Request_Field;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables
}
