/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Dao.BloodBankDao;
import model.BloodBank;

import javax.swing.*;
import java.awt.*;
import java.util.List;

import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ACER
 */
public class BloodBanks extends javax.swing.JFrame {

    /**
     * Creates new form BloodBanks
     */
    public BloodBanks() {
        initComponents();
        loadBloodBanks();
    }

    private void loadBloodBanks() {
    jPanel1.removeAll();
    jPanel2.removeAll();

    jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
    jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

    List<BloodBank> bloodBanks = BloodBankDao.getAll();

    for (BloodBank bank : bloodBanks) {
        JPanel bankPanel = new JPanel();
        bankPanel.setLayout(new BoxLayout(bankPanel, BoxLayout.Y_AXIS));
        bankPanel.setBorder(BorderFactory.createLineBorder(Color.RED));
        bankPanel.setBackground(Color.WHITE);
        bankPanel.setPreferredSize(new Dimension(300, 100));
        bankPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 100));

        JLabel nameLabel = new JLabel("Name: " + bank.getName());
        JLabel locationLabel = new JLabel("Location: " + bank.getLocation());
        JLabel contactLabel = new JLabel("Contact Number: " + bank.getContact());

        bankPanel.add(nameLabel);
        bankPanel.add(locationLabel);
        bankPanel.add(contactLabel);

        if (bank.getRegion() != null && bank.getRegion().trim().equalsIgnoreCase("In Ktm valley")) {
            jPanel1.add(bankPanel);
        } else {
            jPanel2.add(bankPanel);
        }
    }

    jPanel1.revalidate();
    jPanel1.repaint();
    jPanel2.revalidate();
    jPanel2.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Home_Field = new javax.swing.JButton();
        Stories_Field = new javax.swing.JButton();
        Campaign_Field = new javax.swing.JButton();
        Banks_Field = new javax.swing.JButton();
        Emergency_Field = new javax.swing.JButton();
        Donate_Field = new javax.swing.JButton();
        Request_Field = new javax.swing.JButton();
        Profile_Field = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Blood Link logo (2).jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        Home_Field.setText("Home");
        Home_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_FieldActionPerformed(evt);
            }
        });

        Stories_Field.setText("Blood Stories");
        Stories_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stories_FieldActionPerformed(evt);
            }
        });

        Campaign_Field.setText("Campaign Details");
        Campaign_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campaign_FieldActionPerformed(evt);
            }
        });

        Banks_Field.setText("Blood Banks");
        Banks_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Banks_FieldActionPerformed(evt);
            }
        });

        Emergency_Field.setText("Emergency Requests");
        Emergency_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emergency_FieldActionPerformed(evt);
            }
        });

        Donate_Field.setText("Donate");
        Donate_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Donate_FieldActionPerformed(evt);
            }
        });

        Request_Field.setText("Request");
        Request_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Request_FieldActionPerformed(evt);
            }
        });

        Profile_Field.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profile_icon.png"))); // NOI18N
        Profile_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_FieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Blood Banks");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Major Blood Banks In and Around Kathmandu Valley");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Major Blood Banks Outside Kathmandu Valley");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(487, 487, 487))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home_Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Stories_Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Campaign_Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Banks_Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Emergency_Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Donate_Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Request_Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Profile_Field)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Home_Field)
                            .addComponent(Stories_Field)
                            .addComponent(Campaign_Field)
                            .addComponent(Banks_Field)
                            .addComponent(Emergency_Field)
                            .addComponent(Donate_Field)
                            .addComponent(Request_Field)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Profile_Field)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_FieldActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard=new Dashboard();
         dashboard.setVisible(true);
    }//GEN-LAST:event_Home_FieldActionPerformed

    private void Stories_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stories_FieldActionPerformed
        // TODO add your handling code here:
        Blood_Stories stories=new Blood_Stories();
         stories.setVisible(true);
    }//GEN-LAST:event_Stories_FieldActionPerformed

    private void Campaign_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campaign_FieldActionPerformed
        // TODO add your handling code here:
        CampaignDetails campaign=new CampaignDetails();
        campaign.setVisible(true);
    }//GEN-LAST:event_Campaign_FieldActionPerformed

    private void Banks_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Banks_FieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Banks_FieldActionPerformed

    private void Emergency_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emergency_FieldActionPerformed
        // TODO add your handling code here:
        EmergencyRequest emergency=new EmergencyRequest();
        emergency.setVisible(true);
    }//GEN-LAST:event_Emergency_FieldActionPerformed

    private void Donate_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Donate_FieldActionPerformed
        // TODO add your handling code here:
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_Donate_FieldActionPerformed

    private void Request_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Request_FieldActionPerformed
        // TODO add your handling code here:
        request Request=new request();
        Request.setVisible(true);
    }//GEN-LAST:event_Request_FieldActionPerformed

    private void Profile_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_FieldActionPerformed
        // TODO add your handling code here:
        Profile profile=new Profile();
        profile.setVisible(true);
    }//GEN-LAST:event_Profile_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodBanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodBanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodBanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodBanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodBanks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Banks_Field;
    private javax.swing.JButton Campaign_Field;
    private javax.swing.JButton Donate_Field;
    private javax.swing.JButton Emergency_Field;
    private javax.swing.JButton Home_Field;
    private javax.swing.JButton Profile_Field;
    private javax.swing.JButton Request_Field;
    private javax.swing.JButton Stories_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
