/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Aagaman
 */
import javax.swing.JOptionPane;

public class BookAppointment extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookAppointment.class.getName());

    /**
     * Creates new form BookAppointment
     */
    public BookAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Conditions_Field = new javax.swing.JTextField();
        Time_Field = new javax.swing.JTextField();
        Number_Field = new javax.swing.JTextField();
        Email_Field = new javax.swing.JTextField();
        Name_Field = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        Save_Field = new javax.swing.JButton();
        Cancel_Field = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Book Appointment");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 170, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood Group");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Preferred donation date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Time");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Medical Conditions");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Donated Before?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        Conditions_Field.setText("Do you have any medical conditions?");
        Conditions_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Conditions_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Conditions_FieldFocusLost(evt);
            }
        });
        getContentPane().add(Conditions_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 210, -1));

        Time_Field.setText("Preferred Time");
        Time_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Time_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Time_FieldFocusLost(evt);
            }
        });
        Time_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Time_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Time_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 210, -1));

        Number_Field.setText("Phone Number");
        Number_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Number_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Number_FieldFocusLost(evt);
            }
        });
        getContentPane().add(Number_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 210, -1));

        Email_Field.setText("Email");
        Email_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_FieldFocusLost(evt);
            }
        });
        getContentPane().add(Email_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, -1));

        Name_Field.setText("Enter your full name");
        Name_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Name_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Name_FieldFocusLost(evt);
            }
        });
        getContentPane().add(Name_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 210, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 210, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A−", "B+", "B−", "AB+", "AB−", "O+", "O−" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 210, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        Save_Field.setBackground(new java.awt.Color(102, 204, 255));
        Save_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Save_Field.setForeground(new java.awt.Color(255, 255, 255));
        Save_Field.setText("Save");
        Save_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Save_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        Cancel_Field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cancel_Field.setText("Cancel");
        Cancel_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 600, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Time_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Time_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Time_FieldActionPerformed

    private void Name_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_FieldFocusGained
            if (Name_Field.getText().equals("Enter your full name")) {
        Name_Field.setText("");
    }
    }//GEN-LAST:event_Name_FieldFocusGained

    private void Name_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_FieldFocusLost
          if (Name_Field.getText().isEmpty()) {
        Name_Field.setText("Enter your full name");
    }
    }//GEN-LAST:event_Name_FieldFocusLost

    private void Email_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_FieldFocusGained
         if (Email_Field.getText().equals("Email")) {
        Email_Field.setText("");
    }
    }//GEN-LAST:event_Email_FieldFocusGained

    private void Email_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_FieldFocusLost
          if (Email_Field.getText().isEmpty()) {
        Email_Field.setText("Email");
    }
    }//GEN-LAST:event_Email_FieldFocusLost

    private void Number_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Number_FieldFocusGained
        if (Number_Field.getText().equals("Phone Number")) {
        Number_Field.setText("");
    }
    }//GEN-LAST:event_Number_FieldFocusGained

    private void Number_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Number_FieldFocusLost
        if (Number_Field.getText().isEmpty()) {
        Number_Field.setText("Phone Number");
    }
    }//GEN-LAST:event_Number_FieldFocusLost

    private void Time_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Time_FieldFocusGained
         if (Time_Field.getText().equals("Preferred Time")) {
        Time_Field.setText("");
    }
    }//GEN-LAST:event_Time_FieldFocusGained

    private void Time_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Time_FieldFocusLost
        if (Time_Field.getText().isEmpty()) {
        Time_Field.setText("Preferred Time");
    }
    }//GEN-LAST:event_Time_FieldFocusLost

    private void Conditions_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Conditions_FieldFocusGained
         if (Conditions_Field.getText().equals("Do you have any medical conditions?")) {
        Conditions_Field.setText("");
    }
    }//GEN-LAST:event_Conditions_FieldFocusGained

    private void Conditions_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Conditions_FieldFocusLost
         if (Conditions_Field.getText().isEmpty()) {
        Conditions_Field.setText("Do you have any medical conditions?");
    }
    }//GEN-LAST:event_Conditions_FieldFocusLost

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void Save_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_FieldActionPerformed
 String name = Name_Field.getText();
    String email = Email_Field.getText();
    String phone = Number_Field.getText();
    String time = Time_Field.getText();
    String conditions = Conditions_Field.getText();

    // Basic Validation
    if (name.equals("Enter your full name") || name.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter your full name.");
        return;
    }

    if (email.equals("Email") || email.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a valid email.");
        return;
    }

    if (phone.equals("Phone Number") || phone.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter your phone number.");
        return;
    }

    if (time.equals("Preferred Time") || time.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a preferred time.");
        return;
    }

    if (conditions.equals("Do you have any medical conditions?")) {
        conditions = ""; // Optional field, treat placeholder as blank
    }

    // Simulate saving (replace this with DB code if needed)
    JOptionPane.showMessageDialog(null, "Appointment Saved:\n\n"
            + "Name: " + name + "\n"
            + "Email: " + email + "\n"
            + "Phone: " + phone + "\n"
            + "Preferred Time: " + time + "\n"
            + "Medical Conditions: " + (conditions.isEmpty() ? "None" : conditions));
    }//GEN-LAST:event_Save_FieldActionPerformed

    private void Cancel_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_FieldActionPerformed
        System.out.println("Application closed by user.");
        System.exit(0);
    }//GEN-LAST:event_Cancel_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookAppointment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_Field;
    private javax.swing.JTextField Conditions_Field;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JTextField Name_Field;
    private javax.swing.JTextField Number_Field;
    private javax.swing.JButton Save_Field;
    private javax.swing.JTextField Time_Field;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
