package view;

import Dao.CampaignDao;
import model.Campaign;
import javax.swing.*;
import java.awt.*;
import java.util.List;

public class CampaignDetails extends javax.swing.JFrame {

    public CampaignDetails() {
        initComponents();
        loadCampaigns();  // Load campaigns dynamically
    }

    // Method to load campaigns dynamically into jPanel2
    public void loadCampaigns() {
        jPanel2.removeAll();
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

        List<Campaign> campaigns = CampaignDao.getAllCampaigns();

        for (Campaign c : campaigns) {
            JPanel panel = new JPanel();
            panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
            panel.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            panel.setBackground(new Color(240, 240, 240));
            panel.setMaximumSize(new Dimension(800, 120));  // Fix max height

            JLabel nameLabel = new JLabel("Campaign Name: " + c.getName());
            JLabel dayLabel = new JLabel("Day: " + c.getDay());
            JLabel dateLabel = new JLabel("Date: " + c.getDate());
            JLabel locationLabel = new JLabel("Location: " + c.getLocation());

            

            panel.add(nameLabel);
            panel.add(dayLabel);
            panel.add(dateLabel);
            panel.add(locationLabel);
            
            

            jPanel2.add(panel);
            jPanel2.add(Box.createVerticalStrut(10));  // Vertical spacing between campaigns
        }

        jPanel2.revalidate();
        jPanel2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePage = new javax.swing.JToggleButton();
        BloodStoriesPage = new javax.swing.JToggleButton();
        CampaignDetailsPage = new javax.swing.JToggleButton();
        BloodBanksPage = new javax.swing.JToggleButton();
        EmergencyRequests = new javax.swing.JToggleButton();
        DonatePage = new javax.swing.JToggleButton();
        RequestPage = new javax.swing.JToggleButton();
        ProfilePage = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomePage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HomePage.setText("Home");
        HomePage.setBorder(null);
        HomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageActionPerformed(evt);
            }
        });
        getContentPane().add(HomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 46, 40, -1));

        BloodStoriesPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BloodStoriesPage.setText("Blood Stories");
        BloodStoriesPage.setBorder(null);
        BloodStoriesPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodStoriesPageActionPerformed(evt);
            }
        });
        getContentPane().add(BloodStoriesPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 46, -1, -1));

        CampaignDetailsPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CampaignDetailsPage.setText("Campaign Details");
        CampaignDetailsPage.setBorder(null);
        getContentPane().add(CampaignDetailsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 46, -1, -1));

        BloodBanksPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BloodBanksPage.setText("Blood Banks");
        BloodBanksPage.setBorder(null);
        BloodBanksPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodBanksPageActionPerformed(evt);
            }
        });
        getContentPane().add(BloodBanksPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 46, -1, -1));

        EmergencyRequests.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmergencyRequests.setText("Emergency Requests");
        EmergencyRequests.setBorder(null);
        EmergencyRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyRequestsActionPerformed(evt);
            }
        });
        getContentPane().add(EmergencyRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 46, 120, -1));

        DonatePage.setBackground(new java.awt.Color(255, 0, 0));
        DonatePage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DonatePage.setForeground(new java.awt.Color(255, 255, 255));
        DonatePage.setText("Donate");
        DonatePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonatePageActionPerformed(evt);
            }
        });
        getContentPane().add(DonatePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 39, 91, 32));

        RequestPage.setBackground(new java.awt.Color(255, 0, 0));
        RequestPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RequestPage.setForeground(new java.awt.Color(255, 255, 255));
        RequestPage.setText("Request");
        RequestPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestPageActionPerformed(evt);
            }
        });
        getContentPane().add(RequestPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 39, 91, 32));

        ProfilePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profile_icon.png"))); // NOI18N
        ProfilePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilePageActionPerformed(evt);
            }
        });
        getContentPane().add(ProfilePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 39, 33, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Campaign Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 83, -1, 37));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 850, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bloodlink-icon.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard=new Dashboard();
         dashboard.setVisible(true);
    }//GEN-LAST:event_HomePageActionPerformed

    private void BloodStoriesPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodStoriesPageActionPerformed
        // TODO add your handling code here:
        Blood_Stories stories=new Blood_Stories();
         stories.setVisible(true);
    }//GEN-LAST:event_BloodStoriesPageActionPerformed

    private void BloodBanksPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodBanksPageActionPerformed
        // TODO add your handling code here:
        BloodBanks banks=new BloodBanks();
        banks.setVisible(true);
    }//GEN-LAST:event_BloodBanksPageActionPerformed

    private void EmergencyRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyRequestsActionPerformed
        // TODO add your handling code here:
        EmergencyRequest emergency=new EmergencyRequest();
        emergency.setVisible(true);
    }//GEN-LAST:event_EmergencyRequestsActionPerformed

    private void DonatePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonatePageActionPerformed
        // TODO add your handling code here:
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_DonatePageActionPerformed

    private void RequestPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestPageActionPerformed
        // TODO add your handling code here:
        
request Request=new request();
        Request.setVisible(true);
    }//GEN-LAST:event_RequestPageActionPerformed

    private void ProfilePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilePageActionPerformed
        // TODO add your handling code here:
        
Profile profile=new Profile();
        profile.setVisible(true);
    }//GEN-LAST:event_ProfilePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampaignDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampaignDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampaignDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampaignDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CampaignDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BloodBanksPage;
    private javax.swing.JToggleButton BloodStoriesPage;
    private javax.swing.JToggleButton CampaignDetailsPage;
    private javax.swing.JToggleButton DonatePage;
    private javax.swing.JToggleButton EmergencyRequests;
    private javax.swing.JToggleButton HomePage;
    private javax.swing.JToggleButton ProfilePage;
    private javax.swing.JToggleButton RequestPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
