/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author VICTUS
 */
public class CheckEligibility extends javax.swing.JFrame {

    /**
     * Creates new form CheckEligibility
     */
    public CheckEligibility() {
        initComponents();
        buttonGroup1.add(Yes1);
        buttonGroup1.add(No1);
        
        buttonGroup2.add(Yes2);
        buttonGroup2.add(No2);
        
        buttonGroup3.add(Yes3);
        buttonGroup3.add(No3);
        
        buttonGroup4.add(Yes4);
        buttonGroup4.add(No4);
       
        buttonGroup5.add(Yes5);
        buttonGroup5.add(No5);
        
        buttonGroup6.add(Yes6);
        buttonGroup6.add(No6);
        
        buttonGroup7.add(Yes7);
        buttonGroup7.add(No7);
        
        buttonGroup8.add(Yes8);
        buttonGroup8.add(No8);
        
        buttonGroup9.add(Yes9);
        buttonGroup9.add(No9);
        
        buttonGroup10.add(Yes10);
        buttonGroup10.add(No10);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        BloodLinkIcon = new javax.swing.JLabel();
        HomePage = new javax.swing.JButton();
        BloodStoriesPage = new javax.swing.JButton();
        CampaignDetailsPage = new javax.swing.JButton();
        BloodBanksPage = new javax.swing.JButton();
        EmergencyRequestsPage = new javax.swing.JButton();
        DonatePage = new javax.swing.JButton();
        RequestPage = new javax.swing.JButton();
        ProfileIcon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CheckEligibilityPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Question1 = new javax.swing.JLabel();
        Yes1 = new javax.swing.JRadioButton();
        Question2 = new javax.swing.JLabel();
        No1 = new javax.swing.JRadioButton();
        Question3 = new javax.swing.JLabel();
        Yes2 = new javax.swing.JRadioButton();
        No2 = new javax.swing.JRadioButton();
        Yes3 = new javax.swing.JRadioButton();
        No3 = new javax.swing.JRadioButton();
        Question4 = new javax.swing.JLabel();
        Yes4 = new javax.swing.JRadioButton();
        No4 = new javax.swing.JRadioButton();
        Question5 = new javax.swing.JLabel();
        Yes5 = new javax.swing.JRadioButton();
        No5 = new javax.swing.JRadioButton();
        Question6 = new javax.swing.JLabel();
        Yes6 = new javax.swing.JRadioButton();
        No6 = new javax.swing.JRadioButton();
        Question7 = new javax.swing.JLabel();
        Yes7 = new javax.swing.JRadioButton();
        No7 = new javax.swing.JRadioButton();
        Question8 = new javax.swing.JLabel();
        Yes8 = new javax.swing.JRadioButton();
        No8 = new javax.swing.JRadioButton();
        Question9 = new javax.swing.JLabel();
        Yes9 = new javax.swing.JRadioButton();
        No9 = new javax.swing.JRadioButton();
        Question10 = new javax.swing.JLabel();
        Yes10 = new javax.swing.JRadioButton();
        No10 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        SubmitAnswerButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BloodLinkIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bloodlink-icon.jpg"))); // NOI18N
        getContentPane().add(BloodLinkIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 18, -1, -1));

        HomePage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HomePage.setText("Home");
        HomePage.setBorder(null);
        HomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageActionPerformed(evt);
            }
        });
        getContentPane().add(HomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 42, -1, -1));

        BloodStoriesPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BloodStoriesPage.setText("Blood Stories");
        BloodStoriesPage.setBorder(null);
        getContentPane().add(BloodStoriesPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 42, -1, -1));

        CampaignDetailsPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CampaignDetailsPage.setText("Campaign Details");
        CampaignDetailsPage.setBorder(null);
        getContentPane().add(CampaignDetailsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 42, -1, -1));

        BloodBanksPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BloodBanksPage.setText("Blood Banks");
        BloodBanksPage.setBorder(null);
        getContentPane().add(BloodBanksPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 42, -1, -1));

        EmergencyRequestsPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmergencyRequestsPage.setText("Emergency Requests");
        EmergencyRequestsPage.setBorder(null);
        getContentPane().add(EmergencyRequestsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 42, -1, -1));

        DonatePage.setBackground(new java.awt.Color(255, 0, 0));
        DonatePage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DonatePage.setForeground(new java.awt.Color(255, 255, 255));
        DonatePage.setText("Donate");
        getContentPane().add(DonatePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 35, 90, 31));

        RequestPage.setBackground(new java.awt.Color(255, 0, 0));
        RequestPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RequestPage.setForeground(new java.awt.Color(255, 255, 255));
        RequestPage.setText("Request");
        getContentPane().add(RequestPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 35, 88, 31));

        ProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile_icon.png"))); // NOI18N
        ProfileIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileIconActionPerformed(evt);
            }
        });
        getContentPane().add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 35, 32, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        CheckEligibilityPage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CheckEligibilityPage.setForeground(new java.awt.Color(255, 0, 0));
        CheckEligibilityPage.setText("Check Eligibility");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(CheckEligibilityPage, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckEligibilityPage, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Question1.setText("1. Have you donated blood in the past 3 months (for men) or 4 months (for women)?");

        Yes1.setText("Yes");
        Yes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Yes1ActionPerformed(evt);
            }
        });

        Question2.setText("2. Have you had any recent illnesses, infections, or fever in the past 2 weeks?");

        No1.setText("No");

        Question3.setText("3. Do you have or have you ever had any of the following conditions?  (Heart disease, Cancer, Epilepsy, Diabetes requiring insulin, Hepatitis B or C, HIV/AIDS)");

        Yes2.setText("Yes");

        No2.setText("No");

        Yes3.setText("Yes");

        No3.setText("No");

        Question4.setText("4. Have you had any surgeries or blood transfusions in the past 6–12 months?");

        Yes4.setText("Yes");

        No4.setText("No");

        Question5.setText("5. Have you traveled to or lived in countries with a high risk of malaria, Zika, or other infectious diseases in the last 12 months?");

        Yes5.setText("Yes");

        No5.setText("No");

        Question6.setText("6. Have you had any tattoos, piercings, or acupuncture treatments in the past 6 months?");

        Yes6.setText("Yes");
        Yes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Yes6ActionPerformed(evt);
            }
        });

        No6.setText("No");

        Question7.setText("7. Have you had unprotected sex with a new or multiple partners in the last 3 months?");

        Yes7.setText("Yes");

        No7.setText("No");

        Question8.setText("8. Are you currently pregnant, or have you given birth in the past 6 months?");

        Yes8.setText("Yes");
        Yes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Yes8ActionPerformed(evt);
            }
        });

        No8.setText("No");

        Question9.setText("9. Are you currently breastfeeding?");

        Yes9.setText("Yes");

        No9.setText("No");

        Question10.setText("10. Are you taking any medications right now?");

        Yes10.setText("Yes");

        No10.setText("No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question4, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question3)
                            .addComponent(Question6, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question7, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Question8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Question5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Question10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                                .addComponent(Question9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(No4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(No5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(No9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(No10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Yes10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Question1)
                .addGap(12, 12, 12)
                .addComponent(Yes1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yes3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yes4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yes5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yes6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yes7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yes8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yes9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yes10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No10)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 330));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        SubmitAnswerButton.setBackground(new java.awt.Color(255, 0, 0));
        SubmitAnswerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubmitAnswerButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitAnswerButton.setText("SUBMIT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(SubmitAnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubmitAnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomePageActionPerformed

    private void ProfileIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileIconActionPerformed

    private void Yes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Yes6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Yes6ActionPerformed

    private void Yes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Yes8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Yes8ActionPerformed

    private void Yes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Yes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Yes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckEligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CheckEligibility().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BloodBanksPage;
    private javax.swing.JLabel BloodLinkIcon;
    private javax.swing.JButton BloodStoriesPage;
    private javax.swing.JButton CampaignDetailsPage;
    private javax.swing.JLabel CheckEligibilityPage;
    private javax.swing.JButton DonatePage;
    private javax.swing.JButton EmergencyRequestsPage;
    private javax.swing.JButton HomePage;
    private javax.swing.JRadioButton No1;
    private javax.swing.JRadioButton No10;
    private javax.swing.JRadioButton No2;
    private javax.swing.JRadioButton No3;
    private javax.swing.JRadioButton No4;
    private javax.swing.JRadioButton No5;
    private javax.swing.JRadioButton No6;
    private javax.swing.JRadioButton No7;
    private javax.swing.JRadioButton No8;
    private javax.swing.JRadioButton No9;
    private javax.swing.JButton ProfileIcon;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question10;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question4;
    private javax.swing.JLabel Question5;
    private javax.swing.JLabel Question6;
    private javax.swing.JLabel Question7;
    private javax.swing.JLabel Question8;
    private javax.swing.JLabel Question9;
    private javax.swing.JButton RequestPage;
    private javax.swing.JToggleButton SubmitAnswerButton;
    private javax.swing.JRadioButton Yes1;
    private javax.swing.JRadioButton Yes10;
    private javax.swing.JRadioButton Yes2;
    private javax.swing.JRadioButton Yes3;
    private javax.swing.JRadioButton Yes4;
    private javax.swing.JRadioButton Yes5;
    private javax.swing.JRadioButton Yes6;
    private javax.swing.JRadioButton Yes7;
    private javax.swing.JRadioButton Yes8;
    private javax.swing.JRadioButton Yes9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}

