/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author VICTUS
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form checkeligibility
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homepage = new javax.swing.JButton();
        BloodStoriesPage = new javax.swing.JButton();
        CampaignDetailspage = new javax.swing.JButton();
        BloodBanksPage = new javax.swing.JButton();
        EmergencyRequestsPage = new javax.swing.JButton();
        DonatePage = new javax.swing.JButton();
        RequestPage = new javax.swing.JButton();
        ProfilePage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homepage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homepage.setText("Home");
        homepage.setBorder(null);
        homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageActionPerformed(evt);
            }
        });
        getContentPane().add(homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 28, -1, -1));

        BloodStoriesPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BloodStoriesPage.setText("Blood Stories");
        BloodStoriesPage.setBorder(null);
        BloodStoriesPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodStoriesPageActionPerformed(evt);
            }
        });
        getContentPane().add(BloodStoriesPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 28, -1, -1));

        CampaignDetailspage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CampaignDetailspage.setText("Campaign Details");
        CampaignDetailspage.setBorder(null);
        getContentPane().add(CampaignDetailspage, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 28, -1, -1));

        BloodBanksPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BloodBanksPage.setText("Blood Banks ");
        BloodBanksPage.setBorder(null);
        BloodBanksPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodBanksPageActionPerformed(evt);
            }
        });
        getContentPane().add(BloodBanksPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 28, -1, -1));

        EmergencyRequestsPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmergencyRequestsPage.setText("Emergency Requests");
        EmergencyRequestsPage.setBorder(null);
        getContentPane().add(EmergencyRequestsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 28, -1, -1));

        DonatePage.setBackground(new java.awt.Color(255, 0, 0));
        DonatePage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DonatePage.setForeground(new java.awt.Color(255, 255, 255));
        DonatePage.setText("Donate");
        DonatePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonatePageActionPerformed(evt);
            }
        });
        getContentPane().add(DonatePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 78, 32));

        RequestPage.setBackground(new java.awt.Color(255, 0, 0));
        RequestPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RequestPage.setForeground(new java.awt.Color(255, 255, 255));
        RequestPage.setText("Request");
        getContentPane().add(RequestPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 21, -1, 32));

        ProfilePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile_icon.png"))); // NOI18N
        ProfilePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilePageActionPerformed(evt);
            }
        });
        getContentPane().add(ProfilePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 21, 39, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bloodlink-icon.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 16, 123, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Introduction");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 98, -1, -1));

        jLabel3.setText("Blood Links is a platform designed to ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 136, -1, -1));

        jLabel4.setText("streamline blood donation and request");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 158, -1, -1));

        jLabel5.setText("processes, aiming to ensure timely access to");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 180, -1, -1));

        jLabel6.setText("blood for those in need. It connects donors,");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 202, -1, -1));

        jLabel7.setText("recipients, blood banks, hospitals, and");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 224, -1, -1));

        jLabel8.setText("laboratories across Nepal.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 246, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Latest Campaign");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 291, -1, -1));

        jLabel10.setText("The Hospitality Sales and Marketing ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 329, -1, -1));

        jLabel11.setText("Association (HSAMA), in partnership with the");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 351, -1, -1));

        jLabel12.setText("Nepal Red Cross Society, is hosted a mega ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 373, -1, -1));

        jLabel13.setText("blood donation program on February 8, 2025 ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 395, -1, -1));

        jLabel14.setText("(Magh 26, 2081). The event took place at Hotel");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 417, -1, -1));

        jLabel15.setText("Crystal Pashupati in Gaushala, operated by");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 439, -1, -1));

        jLabel16.setText("Trade Tower Group, as confirmed by Dipak");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 461, -1, -1));

        jLabel17.setText("Pokhrel, Director of Sales and Marketing at ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 483, -1, -1));

        jLabel18.setText("Paradise Inn.");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 505, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/introduction.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 103, 264, -1));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 271, 43, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/latest.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 337, 300, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/slogan.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 170, 176, 231));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white.jpg"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BloodStoriesPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodStoriesPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodStoriesPageActionPerformed

    private void BloodBanksPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodBanksPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodBanksPageActionPerformed

    private void DonatePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonatePageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonatePageActionPerformed

    private void ProfilePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilePageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfilePageActionPerformed

    private void homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homepageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BloodBanksPage;
    private javax.swing.JButton BloodStoriesPage;
    private javax.swing.JButton CampaignDetailspage;
    private javax.swing.JButton DonatePage;
    private javax.swing.JButton EmergencyRequestsPage;
    private javax.swing.JButton ProfilePage;
    private javax.swing.JButton RequestPage;
    private javax.swing.JButton homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
