/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author mansh
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_field = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Email_Field = new javax.swing.JTextField();
        Username_Field = new javax.swing.JTextField();
        Password_Field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_field.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Login_field.setText("         Log In ");
        getContentPane().add(Login_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 50, 135, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Log In");
        jButton2.setBorder(null);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 280, 97, 34));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Reset Password");
        jButton3.setBorder(null);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 345, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 0, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sign Up");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 373, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Don't have an account?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 345, 128, -1));

        Email_Field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Email_Field.setText("              Email");
        Email_Field.setBorder(null);
        Email_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_FieldFocusLost(evt);
            }
        });
        Email_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Email_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 98, 200, 36));

        Username_Field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Username_Field.setText("             Username");
        Username_Field.setBorder(null);
        Username_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Username_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Username_FieldFocusLost(evt);
            }
        });
        Username_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Username_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 158, 200, 36));

        Password_Field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password_Field.setText("             Password");
        Password_Field.setBorder(null);
        Password_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_FieldFocusLost(evt);
            }
        });
        getContentPane().add(Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 212, 200, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mansh\\Downloads\\Screenshot-2025-05-23-165749.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 28, 95, 33));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mansh\\OneDrive\\画像\\Screenshots\\Screenshot 2025-05-30 124914.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 6, 540, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Email_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_FieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Email_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_FieldFocusGained
        // TODO add your handling code here:
        if (Email_Field.getText().trim().equals("Email")) {
        Email_Field.setText("");
    }
    }//GEN-LAST:event_Email_FieldFocusGained

    private void Username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_FieldActionPerformed

    private void Email_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_FieldFocusLost
        // TODO add your handling code here:
        if (Email_Field.getText().trim().isEmpty()) {
        Email_Field.setText("Email");
    }
    }//GEN-LAST:event_Email_FieldFocusLost

    private void Username_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_FieldFocusGained
        // TODO add your handling code here:
        if (Username_Field.getText().trim().equals("Username")) {
        Username_Field.setText("");
    }
    }//GEN-LAST:event_Username_FieldFocusGained

    private void Username_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_FieldFocusLost
        // TODO add your handling code here:
         if (Username_Field.getText().trim().isEmpty()) {
        Username_Field.setText("Username");
    }
    }//GEN-LAST:event_Username_FieldFocusLost

    private void Password_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_FieldFocusGained
        // TODO add your handling code here:
        if (Password_Field.getText().trim().equals("Password")) {
        Password_Field.setText("");
    }
    }//GEN-LAST:event_Password_FieldFocusGained

    private void Password_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_FieldFocusLost
        // TODO add your handling code here:
         if (Password_Field.getText().trim().isEmpty()) {
        Password_Field.setText("Password");
    }
    }//GEN-LAST:event_Password_FieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email_Field;
    private javax.swing.JLabel Login_field;
    private javax.swing.JTextField Password_Field;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
