/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Aagaman
 */
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class request extends javax.swing.JPanel {

    /**
     * Creates new form request
     */
    public request() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Patient_field = new javax.swing.JTextField();
        Contact_field = new javax.swing.JTextField();
        Blood_field = new javax.swing.JTextField();
        Note_field = new javax.swing.JTextField();
        Requisition_field = new javax.swing.JTextField();
        Submit_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 101, 86, -1));

        Patient_field.setBackground(new java.awt.Color(204, 204, 204));
        Patient_field.setText("Patient's Name");
        Patient_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Patient_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Patient_fieldFocusLost(evt);
            }
        });
        Patient_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_fieldActionPerformed(evt);
            }
        });
        add(Patient_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 148, 102, 42));

        Contact_field.setBackground(new java.awt.Color(204, 204, 204));
        Contact_field.setText("Contact Number");
        Contact_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Contact_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Contact_fieldFocusLost(evt);
            }
        });
        Contact_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contact_fieldActionPerformed(evt);
            }
        });
        add(Contact_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 148, 105, 42));

        Blood_field.setBackground(new java.awt.Color(204, 204, 204));
        Blood_field.setText("Blood Group");
        Blood_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Blood_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Blood_fieldFocusLost(evt);
            }
        });
        Blood_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blood_fieldActionPerformed(evt);
            }
        });
        add(Blood_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 247, 102, 42));

        Note_field.setBackground(new java.awt.Color(204, 204, 204));
        Note_field.setText("Note:");
        Note_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Note_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Note_fieldFocusLost(evt);
            }
        });
        add(Note_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 323, 102, 46));

        Requisition_field.setBackground(new java.awt.Color(204, 204, 204));
        Requisition_field.setText("Requisition Form");
        Requisition_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Requisition_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Requisition_fieldFocusLost(evt);
            }
        });
        Requisition_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Requisition_fieldActionPerformed(evt);
            }
        });
        add(Requisition_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 247, -1, 42));

        Submit_button.setBackground(new java.awt.Color(204, 204, 204));
        Submit_button.setForeground(new java.awt.Color(255, 0, 0));
        Submit_button.setText("Submit");
        Submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_buttonActionPerformed(evt);
            }
        });
        add(Submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 376, 86, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 6, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Blood Stories");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 6, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Campaign Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 6, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Blood Banks");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 6, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Emergency Requests");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 6, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Donate");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 6, -1, -1));

        jButton8.setBackground(new java.awt.Color(255, 102, 102));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Request");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 6, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image (1).png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void Blood_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blood_fieldActionPerformed
        Requisition_field.requestFocus();
    }//GEN-LAST:event_Blood_fieldActionPerformed

    private void Patient_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_fieldActionPerformed
        Contact_field.requestFocus();
    }//GEN-LAST:event_Patient_fieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void Submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_buttonActionPerformed
      String name = Patient_field.getText().trim();
    String contact = Contact_field.getText().trim();
    String bloodGroup = Blood_field.getText().trim();
    String requisition = Requisition_field.getText().trim();
    String note = Note_field.getText().trim();

    if (name.isEmpty() || contact.isEmpty() || bloodGroup.isEmpty()) {
        System.out.println("Please fill all required fields!");
        return;
    }

    System.out.println("Submitted Successfully!");
    System.out.println("Patient Name: " + name);
    System.out.println("Contact: " + contact);
    System.out.println("Blood Group: " + bloodGroup);
    System.out.println("Requisition: " + requisition);
    System.out.println("Note: " + note);
    }//GEN-LAST:event_Submit_buttonActionPerformed

    private void Contact_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contact_fieldActionPerformed
        Blood_field.requestFocus();
    }//GEN-LAST:event_Contact_fieldActionPerformed

    private void Patient_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Patient_fieldFocusGained
       Patient_field.setBackground(Color.YELLOW);
    }//GEN-LAST:event_Patient_fieldFocusGained

    private void Patient_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Patient_fieldFocusLost
        Patient_field.setBackground(Color.WHITE);
    }//GEN-LAST:event_Patient_fieldFocusLost

    private void Blood_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Blood_fieldFocusGained
        Blood_field.setBackground(Color.YELLOW);
    }//GEN-LAST:event_Blood_fieldFocusGained

    private void Blood_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Blood_fieldFocusLost
        Blood_field.setBackground(Color.WHITE);
    }//GEN-LAST:event_Blood_fieldFocusLost

    private void Note_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Note_fieldFocusGained
       if (Note_field.getText().equals("Note:")) {
        Note_field.setText("");
        Note_field.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_Note_fieldFocusGained

    private void Note_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Note_fieldFocusLost
       if (Note_field.getText().isEmpty()) {
        Note_field.setText("Note:");
        Note_field.setForeground(Color.GRAY);
    }
    }//GEN-LAST:event_Note_fieldFocusLost

    private void Contact_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Contact_fieldFocusGained
        Contact_field.setBackground(Color.YELLOW);
    }//GEN-LAST:event_Contact_fieldFocusGained

    private void Contact_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Contact_fieldFocusLost
        Contact_field.setBackground(Color.WHITE);
    }//GEN-LAST:event_Contact_fieldFocusLost

    private void Requisition_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Requisition_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Requisition_fieldActionPerformed

    private void Requisition_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Requisition_fieldFocusLost
        if (Requisition_field.getText().isEmpty()) {
            Requisition_field.setText("Requisition Form");
            Requisition_field.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_Requisition_fieldFocusLost

    private void Requisition_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Requisition_fieldFocusGained
        if (Requisition_field.getText().equals("Requisition Form")) {
            Requisition_field.setText("");
            Requisition_field.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_Requisition_fieldFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Blood_field;
    private javax.swing.JTextField Contact_field;
    private javax.swing.JTextField Note_field;
    private javax.swing.JTextField Patient_field;
    private javax.swing.JTextField Requisition_field;
    private javax.swing.JButton Submit_button;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
 public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("Blood Request Form");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.getContentPane().add(new request());
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }
}

