/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.*;
import javax.swing.*;



/**
 *
 * @author ACER
 */
public class Reset_Password extends javax.swing.JFrame {

    /**
     * Creates new form resetpassword
     */
    public Reset_Password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        old_field = new javax.swing.JTextField();
        new_field = new javax.swing.JTextField();
        confirm_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Reset Password");

        jLabel2.setText("Email:");

        jLabel3.setText("Old Password:");

        jLabel4.setText("New Password:");

        jLabel5.setText("Confirm Password:");

        email_field.setText("Enter your email");
        email_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_fieldFocusLost(evt);
            }
        });

        old_field.setText("Old Password");
        old_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                old_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                old_fieldFocusLost(evt);
            }
        });

        new_field.setText("New Password");
        new_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_fieldFocusLost(evt);
            }
        });

        confirm_field.setText("Confirm Password");
        confirm_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirm_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirm_fieldFocusLost(evt);
            }
        });
        confirm_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_fieldActionPerformed(evt);
            }
        });

        jButton1.setText("Reset Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton1)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2)
                    .addComponent(email_field, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(new_field)
                    .addComponent(confirm_field)
                    .addComponent(old_field))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 200, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(old_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(new_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusGained
        // TODO add your handling code here:
        if (email_field.getText().equals("Enter your email")) {
        email_field.setText("");
    }

    }//GEN-LAST:event_email_fieldFocusGained

    private void email_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusLost
        // TODO add your handling code here:
        if (email_field.getText().isEmpty()) {
        email_field.setText("Enter your email");
    }
    }//GEN-LAST:event_email_fieldFocusLost

    private void old_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_old_fieldFocusGained
        // TODO add your handling code here:
         if (old_field.getText().equals("Old Password")) {
        old_field.setText("");
    }
    }//GEN-LAST:event_old_fieldFocusGained

    private void old_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_old_fieldFocusLost
        // TODO add your handling code here:
        if (old_field.getText().isEmpty()) {
        old_field.setText("Old Password");
    }
    }//GEN-LAST:event_old_fieldFocusLost

    private void new_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_fieldFocusGained
        // TODO add your handling code here:
        if (new_field.getText().equals("New Password")) {
        new_field.setText("");
    }
    }//GEN-LAST:event_new_fieldFocusGained

    private void new_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_fieldFocusLost
        // TODO add your handling code here:
        if (new_field.getText().isEmpty()) {
        new_field.setText("New Password");
    }
    }//GEN-LAST:event_new_fieldFocusLost

    private void confirm_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_fieldFocusGained
        // TODO add your handling code here:
        if (confirm_field.getText().equals("Confirm Password")) {
        confirm_field.setText("");
    }
    }//GEN-LAST:event_confirm_fieldFocusGained

    private void confirm_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_fieldActionPerformed

    private void confirm_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_fieldFocusLost
        // TODO add your handling code here:
        if (confirm_field.getText().isEmpty()) {
        confirm_field.setText("Confirm Password");
    }
    }//GEN-LAST:event_confirm_fieldFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          resetPasswordAction();

    // Close the window after attempting to reset
    // (You can move this inside resetPasswordAction if you want to close only on success)
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetPasswordAction(){
        String email=email_field.getText().trim();
        String oldPassword=old_field.getText().trim();
        String newPassword=new_field.getText().trim();
        String confirmPassword=confirm_field.getText().trim();
        
        if(email.isEmpty() || oldPassword.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all fields");
            return;
          
        }
        if(!newPassword.endsWith(confirmPassword)){
            JOptionPane.showMessageDialog(this, "New and Confirm password do not match.");
            return;
        }
        try{
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodlink", "root", "IT$universe31");
            
            String query = "SELECT * FROM users WHERE email = ? AND password = ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, email);
            ps.setString(2, oldPassword);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String updateQuery = "UPDATE users SET password = ? WHERE email = ?";
                PreparedStatement updatePs = conn.prepareStatement(updateQuery);
                updatePs.setString(1, newPassword);
                updatePs.setString(2, email);

                int updated = updatePs.executeUpdate();

                if (updated > 0) {
                    JOptionPane.showMessageDialog(this, "Password updated successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update password.");
                }

                updatePs.close();
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect username or old password.");
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reset_Password().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirm_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField new_field;
    private javax.swing.JTextField old_field;
    // End of variables declaration//GEN-END:variables
}

