/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.*;
import javax.swing.*;



/**
 *
 * @author ACER
 */
public class Reset_Password extends javax.swing.JFrame {

    /**
     * Creates new form resetpassword
     */
    public Reset_Password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        old_field = new javax.swing.JTextField();
        new_field = new javax.swing.JTextField();
        confirm_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Reset Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 53, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 107, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Old Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 147, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 190, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 230, -1, 26));

        email_field.setText("Enter your email");
        email_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_fieldFocusLost(evt);
            }
        });
        getContentPane().add(email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 104, 150, -1));

        old_field.setText("Old Password");
        old_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                old_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                old_fieldFocusLost(evt);
            }
        });
        getContentPane().add(old_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 144, 150, -1));

        new_field.setText("New Password");
        new_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_fieldFocusLost(evt);
            }
        });
        getContentPane().add(new_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 187, 150, -1));

        confirm_field.setText("Confirm Password");
        confirm_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirm_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirm_fieldFocusLost(evt);
            }
        });
        confirm_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(confirm_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 232, 150, -1));

        jButton1.setText("Reset Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 274, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 274, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bd.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusGained
        // TODO add your handling code here:
        if (email_field.getText().equals("Enter your email")) {
        email_field.setText("");
    }

    }//GEN-LAST:event_email_fieldFocusGained

    private void email_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusLost
        // TODO add your handling code here:
        if (email_field.getText().isEmpty()) {
        email_field.setText("Enter your email");
    }
    }//GEN-LAST:event_email_fieldFocusLost

    private void old_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_old_fieldFocusGained
        // TODO add your handling code here:
         if (old_field.getText().equals("Old Password")) {
        old_field.setText("");
    }
    }//GEN-LAST:event_old_fieldFocusGained

    private void old_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_old_fieldFocusLost
        // TODO add your handling code here:
        if (old_field.getText().isEmpty()) {
        old_field.setText("Old Password");
    }
    }//GEN-LAST:event_old_fieldFocusLost

    private void new_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_fieldFocusGained
        // TODO add your handling code here:
        if (new_field.getText().equals("New Password")) {
        new_field.setText("");
    }
    }//GEN-LAST:event_new_fieldFocusGained

    private void new_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_fieldFocusLost
        // TODO add your handling code here:
        if (new_field.getText().isEmpty()) {
        new_field.setText("New Password");
    }
    }//GEN-LAST:event_new_fieldFocusLost

    private void confirm_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_fieldFocusGained
        // TODO add your handling code here:
        if (confirm_field.getText().equals("Confirm Password")) {
        confirm_field.setText("");
    }
    }//GEN-LAST:event_confirm_fieldFocusGained

    private void confirm_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_fieldActionPerformed

    private void confirm_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_fieldFocusLost
        // TODO add your handling code here:
        if (confirm_field.getText().isEmpty()) {
        confirm_field.setText("Confirm Password");
    }
    }//GEN-LAST:event_confirm_fieldFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          resetPasswordAction();

    // Close the window after attempting to reset
    // (You can move this inside resetPasswordAction if you want to close only on success)
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetPasswordAction(){
        String email=email_field.getText().trim();
        String oldPassword=old_field.getText().trim();
        String newPassword=new_field.getText().trim();
        String confirmPassword=confirm_field.getText().trim();
        
        if(email.isEmpty() || oldPassword.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all fields");
            return;
          
        }
        if(!newPassword.endsWith(confirmPassword)){
            JOptionPane.showMessageDialog(this, "New and Confirm password do not match.");
            return;
        }
        try{
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodlink", "root", "IT$universe31");
            
            String query = "SELECT * FROM users WHERE email = ? AND password = ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, email);
            ps.setString(2, oldPassword);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String updateQuery = "UPDATE users SET password = ? WHERE email = ?";
                PreparedStatement updatePs = conn.prepareStatement(updateQuery);
                updatePs.setString(1, newPassword);
                updatePs.setString(2, email);

                int updated = updatePs.executeUpdate();

                if (updated > 0) {
                    JOptionPane.showMessageDialog(this, "Password updated successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update password.");
                }

                updatePs.close();
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect username or old password.");
            }

            rs.close();
            ps.close();
            conn.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reset_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reset_Password().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirm_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField new_field;
    private javax.swing.JTextField old_field;
    // End of variables declaration//GEN-END:variables
}

